#!/bin/sh
echo "tas5805 trim tool version:v8.0"
echo "Auther:shenh@tcl.com"

caculate_md5sum(){
  md5sum $1 >> $2 		
}

echo "remove old trim file"
rm -rf *.trim*
echo "remove old checksum file"
rm -rf md5sum_*
echo "remove old final file"
rm -rf final*.h

for file in *.h
do
    echo "prepare temp file"
    cp $file $file.temp

    echo "start to trim tas5805 input mix data"
    sed -n -e '68,89p' $file.temp > $file.trim.input.h
    sed -i -e '2a{ 0x7f, 0x00 },' $file.trim.input.h
    sed -i -e '3s/^/\t/g' $file.trim.input.h
    sed -i -e '5a{ 0x00, 0x00 },' $file.trim.input.h
    sed -i -e '6s/^/\t/g' $file.trim.input.h
    caculate_md5sum $file.trim.input.h md5sum_input.txt
    #add file header comment
    sed -i -e '1i//'$file'' $file.trim.input.h
    sed -i -e '1s/.h$/_input/g' $file.trim.input.h
    sed -i -e '1icfg_reg '$file'[] = {' $file.trim.input.h
    sed -i -e '1s/.h/_input/g' $file.trim.input.h
    sed -i -e '$a};' $file.trim.input.h

    echo "remove input mix data from temp file"
    sed -i -e '73,89d' $file.temp


    echo "start to trim tas5805 eq data"
    sed -n -e '68,851p' $file.temp > $file.trim.eq.h
    sed -i -e '4,175d' $file.trim.eq.h
    sed -i -e '2a{ 0x7f, 0x00 },' $file.trim.eq.h
    sed -i -e '3s/^/\t/g' $file.trim.eq.h
    sed -i -e '4s/86/84/g' $file.trim.eq.h
    #remove right channel EQ data
    sed -i -e '311,613d' $file.trim.eq.h
    caculate_md5sum $file.trim.eq.h md5sum_eq.txt
    #add file header comment
    sed -i -e '1i//'$file'' $file.trim.eq.h
    sed -i -e '1s/.h$/_eq/g' $file.trim.eq.h
    #add struct info
    sed -i -e '1icfg_reg '$file'[] = {' $file.trim.eq.h
    sed -i -e '1s/.h/_eq/g' $file.trim.eq.h
    sed -i -e '$a};' $file.trim.eq.h

    echo "start to trim tas5805 AGL data"
    sed -n -e '68,107p' $file.temp > $file.trim.agl.h
    sed -i -e '2a{ 0x7f, 0x00 },' $file.trim.agl.h
    sed -i -e '3s/^/\t/g' $file.trim.agl.h
    sed -i -e '4s/86/84/g' $file.trim.agl.h
    caculate_md5sum $file.trim.agl.h md5sum_agl.txt
    #add file header comment
    sed -i -e '1i//'$file'' $file.trim.agl.h
    sed -i -e '1s/.h$/_agl/g' $file.trim.agl.h
    #add struct info
    sed -i -e '1icfg_reg '$file'[] = {' $file.trim.agl.h
    sed -i -e '1s/.h/_agl/g' $file.trim.agl.h
    sed -i -e '$a};' $file.trim.agl.h

    echo "start to trim tas5805 DRC data"
    sed -n -e '68,1017p' $file.temp > $file.trim.drc.h
    sed -i -e '6,40d' $file.trim.drc.h
    sed -i -e '144,749d' $file.trim.drc.h
    sed -i -e '2a{ 0x7f, 0x00 },' $file.trim.drc.h
    sed -i -e '3s/^/\t/g' $file.trim.drc.h
    caculate_md5sum $file.trim.drc.h md5sum_drc.txt
    #add file header comment
    sed -i -e '1i//'$file'' $file.trim.drc.h
    sed -i -e '1s/.h$/_drc./g' $file.trim.drc.h
    #add struct info
    sed -i -e '1icfg_reg '$file'[] = {' $file.trim.drc.h
    sed -i -e '1s/.h/_drc/g' $file.trim.drc.h
    sed -i -e '$a};' $file.trim.drc.h

    echo "remove temp file"
    rm -rf $file.temp

done

gentime="$(date +%Y/%m/%d/%H:%M:%S)"
#merge all same file to one
for file in *input.h
do
cat $file >> final.input.h
done
sed -i -e '1i//THIS FILE IS GENERATED BY TAS5805 TRIMMING TOOL WITH '$gentime'' final.input.h

for file in *drc.h 
do
cat $file >> final.drc.h
done
sed -i -e '1i//THIS FILE IS GENERATED BY TAS5805 TRIMMING TOOL WITH '$gentime'' final.drc.h

for file in *agl.h 
do
cat $file >> final.agl.h
done
sed -i -e '1i//THIS FILE IS GENERATED BY TAS5805 TRIMMING TOOL WITH '$gentime'' final.agl.h

for file in *eq.h 
do
cat $file >> final.eq.h
done
sed -i -e '1i//THIS FILE IS GENERATED BY TAS5805 TRIMMING TOOL WITH '$gentime'' final.eq.h